<?php

namespace App\Livewire\Admin;

use App\Models\CourseApprovalWorkflow;
use App\Models\MiniCourse;
use App\Models\Organization;
use App\Services\CourseApprovalService;
use Livewire\Component;

class AICourseSettings extends Component
{
    // Settings fields
    public string $approvalMode = 'create_approve';

    public bool $autoGenerateEnabled = false;

    public array $generationTriggers = [];

    public array $notificationRecipients = [];

    public int $maxAutoCoursesPerDay = 10;

    public bool $requireReviewForAiGenerated = true;

    // Pending approvals
    public bool $showApprovalModal = false;

    public ?int $selectedWorkflowId = null;

    public string $reviewNotes = '';

    public string $rejectionReason = '';

    protected CourseApprovalService $approvalService;

    public function boot(CourseApprovalService $approvalService): void
    {
        $this->approvalService = $approvalService;
    }

    public function mount(): void
    {
        $this->loadSettings();
    }

    protected function loadSettings(): void
    {
        $user = auth()->user();
        $org = Organization::find($user->org_id);

        if ($org) {
            $settings = $org->settings['ai_course_settings'] ?? [];

            $this->approvalMode = $settings['approval_mode'] ?? 'create_approve';
            $this->autoGenerateEnabled = $settings['auto_generate_enabled'] ?? false;
            $this->generationTriggers = $settings['generation_triggers'] ?? [];
            $this->notificationRecipients = $settings['notification_recipients'] ?? [];
            $this->maxAutoCoursesPerDay = $settings['max_auto_courses_per_day'] ?? 10;
            $this->requireReviewForAiGenerated = $settings['require_review_for_ai_generated'] ?? true;
        }
    }

    public function saveSettings(): void
    {
        $this->validate([
            'approvalMode' => 'required|in:auto_activate,create_approve,approve_first',
            'maxAutoCoursesPerDay' => 'required|integer|min:1|max:100',
        ]);

        $user = auth()->user();
        $org = Organization::find($user->org_id);

        if ($org) {
            $settings = $org->settings ?? [];
            $settings['ai_course_settings'] = [
                'approval_mode' => $this->approvalMode,
                'auto_generate_enabled' => $this->autoGenerateEnabled,
                'generation_triggers' => $this->generationTriggers,
                'notification_recipients' => $this->notificationRecipients,
                'max_auto_courses_per_day' => $this->maxAutoCoursesPerDay,
                'require_review_for_ai_generated' => $this->requireReviewForAiGenerated,
            ];

            $org->update(['settings' => $settings]);

            $this->dispatch('notify', [
                'type' => 'success',
                'message' => 'AI course settings saved successfully.',
            ]);
        }
    }

    public function toggleTrigger(string $trigger): void
    {
        if (in_array($trigger, $this->generationTriggers)) {
            $this->generationTriggers = array_values(array_diff($this->generationTriggers, [$trigger]));
        } else {
            $this->generationTriggers[] = $trigger;
        }
    }

    public function toggleRecipient(string $recipient): void
    {
        if (in_array($recipient, $this->notificationRecipients)) {
            $this->notificationRecipients = array_values(array_diff($this->notificationRecipients, [$recipient]));
        } else {
            $this->notificationRecipients[] = $recipient;
        }
    }

    // ============================================
    // APPROVAL MANAGEMENT
    // ============================================

    public function getPendingApprovalsProperty()
    {
        $user = auth()->user();

        return $this->approvalService->getPendingApprovals($user->org_id);
    }

    public function getApprovalStatsProperty(): array
    {
        $user = auth()->user();
        $orgId = $user->org_id;

        return [
            'pending' => CourseApprovalWorkflow::pending()
                ->whereHas('course', fn ($q) => $q->where('org_id', $orgId))
                ->count(),
            'approved_this_week' => CourseApprovalWorkflow::approved()
                ->whereHas('course', fn ($q) => $q->where('org_id', $orgId))
                ->where('reviewed_at', '>=', now()->startOfWeek())
                ->count(),
            'rejected_this_week' => CourseApprovalWorkflow::rejected()
                ->whereHas('course', fn ($q) => $q->where('org_id', $orgId))
                ->where('reviewed_at', '>=', now()->startOfWeek())
                ->count(),
            'auto_generated_total' => MiniCourse::where('org_id', $orgId)
                ->autoGenerated()
                ->count(),
        ];
    }

    public function openApprovalModal(int $workflowId): void
    {
        $this->selectedWorkflowId = $workflowId;
        $this->reviewNotes = '';
        $this->rejectionReason = '';
        $this->showApprovalModal = true;
    }

    public function closeApprovalModal(): void
    {
        $this->showApprovalModal = false;
        $this->selectedWorkflowId = null;
        $this->reviewNotes = '';
        $this->rejectionReason = '';
    }

    public function approveCourse(): void
    {
        if (! $this->selectedWorkflowId) {
            return;
        }

        $workflow = CourseApprovalWorkflow::find($this->selectedWorkflowId);

        if ($workflow) {
            $this->approvalService->approve($workflow, auth()->id(), $this->reviewNotes ?: null);

            $this->dispatch('notify', [
                'type' => 'success',
                'message' => 'Course approved and published.',
            ]);
        }

        $this->closeApprovalModal();
    }

    public function rejectCourse(): void
    {
        if (! $this->selectedWorkflowId) {
            return;
        }

        $this->validate([
            'rejectionReason' => 'required|string|min:10',
        ]);

        $workflow = CourseApprovalWorkflow::find($this->selectedWorkflowId);

        if ($workflow) {
            $this->approvalService->reject($workflow, auth()->id(), $this->rejectionReason);

            $this->dispatch('notify', [
                'type' => 'info',
                'message' => 'Course rejected.',
            ]);
        }

        $this->closeApprovalModal();
    }

    public function requestRevision(): void
    {
        if (! $this->selectedWorkflowId) {
            return;
        }

        $this->validate([
            'reviewNotes' => 'required|string|min:10',
        ]);

        $workflow = CourseApprovalWorkflow::find($this->selectedWorkflowId);

        if ($workflow) {
            $this->approvalService->requestRevision($workflow, auth()->id(), $this->reviewNotes);

            $this->dispatch('notify', [
                'type' => 'info',
                'message' => 'Revision requested.',
            ]);
        }

        $this->closeApprovalModal();
    }

    public function quickApprove(int $workflowId): void
    {
        $workflow = CourseApprovalWorkflow::find($workflowId);

        if ($workflow) {
            $this->approvalService->approve($workflow, auth()->id());

            $this->dispatch('notify', [
                'type' => 'success',
                'message' => 'Course approved.',
            ]);
        }
    }

    public function render()
    {
        return view('livewire.admin.ai-course-settings', [
            'pendingApprovals' => $this->pendingApprovals,
            'approvalStats' => $this->approvalStats,
            'approvalModes' => CourseApprovalWorkflow::getWorkflowModes(),
            'triggerOptions' => MiniCourse::getGenerationTriggers(),
        ])->layout('layouts.dashboard', ['title' => 'AI Course Settings']);
    }
}
