<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class OrganizationSettings extends Model
{
    protected $table = 'organization_settings';

    protected $fillable = [
        'org_id',
        'status_labels',
        'risk_labels',
        'settings',
        'terminology',
    ];

    protected $casts = [
        'status_labels' => 'array',
        'risk_labels' => 'array',
        'settings' => 'array',
        'terminology' => 'array',
    ];

    /**
     * Default status labels.
     */
    public const DEFAULT_STATUS_LABELS = [
        'on_track' => 'On Track',
        'at_risk' => 'At Risk',
        'off_track' => 'Off Track',
        'not_started' => 'Not Started',
    ];

    /**
     * Default risk labels.
     */
    public const DEFAULT_RISK_LABELS = [
        'good' => 'Good',
        'low' => 'Low Risk',
        'high' => 'High Risk',
    ];

    /**
     * Default terminology labels (industry-agnostic).
     */
    public const DEFAULT_TERMINOLOGY = [
        // Navigation & general UI
        'home_label' => 'Home',
        'workspace_label' => 'Workspace',
        'settings_label' => 'Settings',
        'help_center_label' => 'Help Center',
        'help_label' => 'Help',
        'help_options_label' => 'Help options',
        'search_help_articles_placeholder' => 'Search help articles...',
        'search_articles_placeholder' => 'Search articles...',
        'search_results_label' => 'Search Results',
        'view_all_results_label' => 'View all results',
        'view_all_search_results_label' => 'View all search results',
        'no_articles_found_label' => 'No articles found',
        'try_advanced_search_label' => 'Try advanced search',
        'popular_articles_label' => 'Popular Articles',
        'featured_articles_label' => 'Featured Articles',
        'browse_by_topic_label' => 'Browse by Topic',
        'browse_by_category_label' => 'Browse by Category',
        'quick_links_label' => 'Quick Links',
        'browse_all_articles_label' => 'Browse all articles',
        'browse_help_center_label' => 'Browse Help Center',
        'page_tour_label' => 'Page Tour',
        'guided_walkthrough_label' => 'Guided walkthrough',
        'contact_support_label' => 'Contact Support',
        'send_us_message_label' => 'Send us a message',
        'help_admin_label' => 'Help Admin',
        'manage_articles_hints_label' => 'Manage articles & hints',
        'close_help_label' => 'Close help',
        'need_help_label' => 'Need help?',
        'show_tooltips_label' => 'Show Tooltips',
        'hide_tooltips_label' => 'Hide Tooltips',
        'help_hints_description_label' => 'Interactive help dots on this page',
        'start_page_tour_label' => 'Start Page Tour',
        'tooltips_step_through_label' => 'Step through all tooltips one-by-one',
        'browse_articles_guides_label' => 'Browse articles and guides',
        'create_tooltips_label' => 'Create Tooltips',
        'exit_creator_mode_label' => 'Exit Creator Mode',
        'help_tips_description_label' => 'Click on elements to add help tips',
        'manage_tooltips_label' => 'Manage Tooltips',
        'view_edit_tooltips_label' => 'View and edit all tooltips',
        'find_answers_label' => 'Find answers to your questions and learn how to use Pulse',
        'showing_results_for_label' => 'Showing results for',
        'all_categories_label' => 'All Categories',
        'all_status_label' => 'All Status',
        'all_statuses_label' => 'All Statuses',
        'drafts_label' => 'Drafts',
        'no_results_found_label' => 'No results found',
        'adjust_search_label' => 'Try adjusting your search or browse our categories',
        'adjust_filters_label' => 'Try adjusting your filters.',
        'min_read_label' => 'min read',
        'views_label' => 'views',
        'articles_label' => 'Articles',
        'article_singular' => 'Article',
        'categories_label' => 'Categories',
        'category_singular' => 'Category',
        'tooltips_label' => 'Tooltips',
        'tooltip_singular' => 'Tooltip',
        'help_documentation_label' => 'Help documentation',
        'organize_articles_label' => 'Organize articles',
        'contextual_tips_label' => 'Contextual page tips',
        'new_article_label' => 'New Article',
        'no_categories_yet_label' => 'No categories yet',
        'create_categories_help_label' => 'Create categories to organize your help articles.',
        'create_first_category_label' => 'Create your first category',
        'parent_label' => 'Parent',
        'inactive_label' => 'Inactive',
        'confirm_delete_category_label' => 'Are you sure you want to delete this category?',
        'name_label' => 'Name',
        'category_name_placeholder' => 'Getting Started',
        'category_slug_placeholder' => 'getting-started',
        'category_description_placeholder' => 'Brief description of this category...',
        'icon_label' => 'Icon',
        'parent_category_label' => 'Parent Category',
        'none_top_level_label' => 'None (Top Level)',
        'sort_order_label' => 'Sort Order',
        'manage_tooltips_page_label' => 'Manage contextual tooltips that appear on each page',
        'visual_editor_label' => 'Visual Editor',
        'open_visual_editor_label' => 'Open visual editor for',
        'this_page_label' => 'this page',
        'no_tooltips_yet_label' => 'No tooltips yet',
        'add_tooltips_help_label' => 'Add tooltips to guide users through the :page page.',
        'add_first_tooltip_label' => 'Add your first tooltip',
        'section_label' => 'Section',
        'selector_label' => 'Selector',
        'position_label' => 'Position',
        'has_video_label' => 'Has video',
        'tooltip_position_label' => 'Tooltip Position',
        'pick_label' => 'Pick',
        'pick_element_label' => 'Pick element visually',
        'pick_element_help_label' => 'Click "Pick" to visually select an element on the page',
        'section_id_label' => 'Section ID',
        'section_id_placeholder' => 'e.g., search-reports',
        'css_selector_label' => 'CSS Selector',
        'selector_placeholder' => 'e.g., [data-help="search-reports"]',
        'tooltip_title_placeholder' => 'Search Reports',
        'tooltip_description_placeholder' => 'Explain what this feature does and how to use it...',
        'video_url_hint_placeholder' => 'Paste Loom, YouTube, or Vimeo URL',
        'confirm_delete_tooltip_label' => 'Are you sure you want to delete this tooltip?',
        'how_tooltips_work_label' => 'How Tooltips Work',
        'section_help_label' => 'Section: Unique identifier (lowercase, hyphens only) e.g.,',
        'selector_help_label' => 'Selector: CSS selector targeting the element, e.g.,',
        'position_help_label' => 'Position: Where the tooltip appears relative to the element',
        'enable_tooltips_help_label' => 'Users enable tooltips via the Help menu → "Show Tooltips"',
        'tooltip_creator_mode_label' => 'Tooltip Creator Mode',
        'click_add_tooltip_label' => 'Click on any element to add a tooltip',
        'page_label' => 'Page',
        'exit_creator_label' => 'Exit Creator',
        'add_new_tooltip_label' => 'Add New Tooltip',
        'for_label' => 'For',
        'tooltip_position_above_label' => 'Above element',
        'tooltip_position_below_label' => 'Below element',
        'tooltip_position_left_label' => 'Left of element',
        'tooltip_position_right_label' => 'Right of element',
        'video_url_supports_label' => 'Supports Loom, YouTube, Vimeo',
        'saving_label' => 'Saving...',
        'slug_label' => 'Slug',
        'select_category_placeholder' => 'Select category...',
        'content_markdown_label' => 'Content (Markdown)',
        'content_markdown_placeholder' => "# Getting Started\n\nWrite your article content here using Markdown...\n\n## Step 1\n\nFirst, do this...\n\n## Step 2\n\nThen do that...",
        'supports_markdown_label' => 'Supports Markdown formatting',
        'article_title_placeholder' => 'How to get started with Pulse',
        'slug_placeholder' => 'how-to-get-started',
        'excerpt_optional_label' => 'Excerpt (optional)',
        'excerpt_placeholder' => 'A brief summary that appears in search results...',
        'auto_generated_excerpt_label' => 'Auto-generated from content if left empty',
        'video_url_optional_label' => 'Video URL (optional)',
        'video_url_placeholder' => 'https://www.youtube.com/watch?v=...',
        'search_keywords_label' => 'Search Keywords',
        'search_keywords_placeholder' => 'getting started, onboarding, new user',
        'search_keywords_help_label' => 'Comma-separated keywords for better search',
        'target_roles_optional_label' => 'Target Roles (optional)',
        'target_roles_help_label' => 'Leave empty to show to all roles',
        'create_article_label' => 'Create Article',
        'edit_article_label' => 'Edit Article',
        'confirm_delete_article_label' => 'Are you sure you want to delete this article?',
        'pages_label' => 'pages',
        'all_articles_label' => 'All Articles',
        'title_label' => 'Title',
        'category_label' => 'Category',
        'feedback_label' => 'Feedback',
        'updated_label' => 'Updated',
        'no_articles_yet_label' => 'No articles yet',
        'create_first_article_label' => 'Create your first article',
        'uncategorized_label' => 'Uncategorized',
        'manage_label' => 'Manage',
        'manage_kb_articles_label' => 'Create and manage knowledge base articles',
        'subcategories_label' => 'Subcategories',
        'articles_in_category_label' => 'Articles',
        'check_back_soon_label' => 'Check back soon for helpful content in this category.',
        'create_first_help_article_label' => 'Create your first help article to get started.',
        'ago_label' => 'ago',
        'related_articles_label' => 'Related Articles',
        'was_this_helpful_label' => 'Was this article helpful?',
        'copied_label' => 'Copied!',
        'copy_link_label' => 'Copy link',
        'share_label' => 'Share',
        'share_article_label' => 'Share this article',
        'email_link_label' => 'Email link',
        'admin_view_label' => 'Admin View',
        'article_id_label' => 'Article ID',
        'still_need_help_label' => 'Still need help?',
        'cant_find_label' => 'Can\'t find what you\'re looking for?',
        'support_team_help_label' => 'Our support team is here to help',
        'most_popular_label' => 'Most Popular',
        'preview_label' => 'Preview',
        'remove_featured_label' => 'Remove from featured',
        'mark_featured_label' => 'Mark as featured',
        'published_label' => 'Published',
        'draft_label' => 'Draft',
        'back_label' => 'Back',
        'general_label' => 'General',
        'marketplace_label' => 'Marketplace',
        'moderation_label' => 'Moderation',
        'collect_label' => 'Collect',
        'distribute_label' => 'Distribute',
        'terminology_label' => 'Terminology',
        'notifications_label' => 'Notifications',
        'profile_label' => 'Profile',
        'security_label' => 'Security',
        'yes_label' => 'Yes',
        'no_label' => 'No',
        'status_label' => 'Status',
        'score_label' => 'Score',
        'history_label' => 'History',
        'assigned_label' => 'Assigned',
        'suggested_label' => 'Suggested',
        'available_label' => 'Available',
        'tag_singular' => 'Tag',
        'tag_plural' => 'Tags',
        'risk_label' => 'Risk',
        'iep_status_label' => 'IEP Status',
        'ell_status_label' => 'ELL Status',
        'details_label' => 'Details',
        'date_of_birth_label' => 'DOB',
        'gender_label' => 'Gender',
        'enrolled_label' => 'Enrolled',
        'strategic_label' => 'Strategic',
        'tab_label' => 'Tab',
        'view_in_label' => 'View in',
        'notes_label' => 'Notes',
        'activity_label' => 'Activity',
        'timeline_label' => 'Timeline',
        'overview_label' => 'Overview',
        'total_label' => 'Total',
        'metrics_label' => 'Metrics',
        'good_standing_label' => 'Good Standing',
        'low_risk_label' => 'Low Risk',
        'high_risk_label' => 'High Risk',
        'active_label' => 'Active',
        'currently_running_label' => 'Currently running',
        'completed_this_week_label' => 'Completed This Week',
        'responses_received_label' => 'Responses received',
        'assignment_singular' => 'Assignment',
        'assignment_plural' => 'Assignments',
        'week_label' => 'Week',
        'back_to_label' => 'Back to',
        'questions_label' => 'Questions',
        'question_singular' => 'Question',
        'required_label' => 'Required',
        'recent_label' => 'Recent',
        'responses_label' => 'Responses',
        'in_progress_label' => 'In Progress',
        'completion_rate_label' => 'Completion Rate',
        'statistics_label' => 'Statistics',
        'delivery_label' => 'Delivery',
        'channel_singular' => 'Channel',
        'channel_plural' => 'Channels',
        'phone_number_label' => 'Phone Number',
        'recipient_singular' => 'Recipient',
        'recipient_plural' => 'Recipients',
        'anonymous_label' => 'Anonymous',
        'enabled_label' => 'Enabled',
        'disabled_label' => 'Disabled',
        'allowed_label' => 'Allowed',
        'ai_follow_up_label' => 'AI Follow-up',
        'voice_responses_label' => 'Voice Responses',
        'push_label' => 'Push',
        'confirm_label' => 'Confirm',
        'confirm_delete_survey_label' => 'Are you sure you want to delete this survey?',
        'web_link_label' => 'Web Link',
        'sms_label' => 'SMS',
        'voice_call_label' => 'Voice Call',
        'whatsapp_label' => 'WhatsApp',
        'all_label' => 'All',
        'type_label' => 'Type',
        'organization_label' => 'Organization',
        'selected_label' => 'Selected',
        'clear_label' => 'Clear',
        'grid_view_label' => 'Grid view',
        'list_view_label' => 'List view',
        'table_view_label' => 'Table view',
        'survey_empty_title' => 'Create your first survey',
        'survey_empty_body' => 'Build surveys to check in on learners using AI assistance, voice, or the form builder.',
        'ai_created_label' => 'AI Created',
        'total_sent_label' => 'Total Sent',
        'pending_label' => 'Pending',
        'delivered_label' => 'Delivered',
        'completed_label' => 'Completed',
        'failed_label' => 'Failed',
        'select_recipients_label' => 'Select Recipients',
        'staff_label' => 'Staff',
        'search_by_label' => 'Search by name or email...',
        'add_phone_manually_label' => 'Add Phone Number Manually',
        'no_recipients_found_label' => 'No recipients found',
        'recipient_selected_label' => 'recipient(s) selected',
        'clear_all_label' => 'Clear all',
        'schedule_delivery_label' => 'Schedule Delivery',
        'send_at_label' => 'Send at a specific date and time',
        'sending_label' => 'Sending...',
        'recent_deliveries_label' => 'Recent Deliveries',
        'no_deliveries_label' => 'No deliveries yet',
        'tips_for_demo_label' => 'Tips for Demo',
        'delivery_successful_label' => 'Delivery Successful!',
        'delivery_complete_label' => 'Delivery Complete',
        'successful_label' => 'Successful',
        'done_label' => 'Done',
        'manual_phone_help_label' => 'For demo: Add your phone number here to receive a live survey',
        'choose_how_label' => 'Choose how you want to build your survey',
        'ai_chat_builder_label' => 'AI Chat Builder',
        'ai_chat_builder_body' => 'Describe your survey in plain language and let AI create questions for you.',
        'natural_conversation_label' => 'Natural conversation',
        'ai_suggestions_label' => 'AI suggestions',
        'quick_refinement_label' => 'Quick refinement',
        'ai_powered_label' => 'AI-Powered',
        'not_configured_label' => 'Not Configured',
        'voice_builder_label' => 'Voice Builder',
        'voice_builder_body' => 'Speak your questions naturally and we\'ll transcribe them into a survey.',
        'hands_free_label' => 'Hands-free creation',
        'audio_transcription_label' => 'Audio transcription',
        'easy_editing_label' => 'Easy editing',
        'form_builder_label' => 'Form Builder',
        'form_builder_body' => 'Build your survey manually with full control over every question.',
        'full_control_label' => 'Full control',
        'question_bank_label' => 'Question bank',
        'advanced_options_label' => 'Advanced options',
        'classic_label' => 'Classic',
        'start_from_template_label' => 'Start from Template',
        'view_all_templates_label' => 'View All Templates',
        'featured_label' => 'Featured',
        'uses_label' => 'uses',
        'ai_assistant_label' => 'AI Survey Assistant',
        'describe_needs_label' => 'Describe your survey needs',
        'finish_edit_label' => 'Finish & Edit',
        'survey_preview_label' => 'Survey Preview',
        'no_questions_yet_label' => 'No questions yet',
        'start_chatting_label' => 'Start chatting to create questions',
        'back_to_mode_selection_label' => 'Back to Mode Selection',
        'voice_survey_builder_label' => 'Voice Survey Builder',
        'voice_survey_builder_body' => 'Speak your survey questions and we\'ll transcribe them',
        'start_recording_label' => 'Start Recording',
        'stop_recording_label' => 'Stop Recording',
        'transcribing_label' => 'Transcribing...',
        'recording_label' => 'Recording... Speak now',
        'processing_audio_label' => 'Processing your audio with AI...',
        'transcription_label' => 'Transcription',
        'extracted_questions_label' => 'Extracted Questions',
        'no_questions_detected_label' => 'No questions detected. Try speaking more clearly.',
        'record_again_label' => 'Record Again',
        'continue_to_editor_label' => 'Continue to Editor',
        'basic_information_label' => 'Basic Information',
        'survey_title_label' => 'Survey Title',
        'description_label' => 'Description',
        'survey_type_label' => 'Survey Type',
        'question_bank_button_label' => 'Question Bank',
        'add_question_label' => 'Add Question',
        'no_questions_added_label' => 'No questions added yet',
        'add_first_question_label' => 'Add your first question',
        'options_label' => 'Options',
        'low_label' => 'Low label',
        'high_label' => 'High label',
        'remove_option_label' => 'Remove option',
        'add_option_label' => 'Add Option',
        'required_question_label' => 'Required question',
        'estimated_duration_label' => 'Estimated Duration',
        'minutes_label' => 'minutes',
        'delivery_channels_label' => 'Delivery Channels',
        'preview_survey_label' => 'Preview Survey',
        'save_as_draft_label' => 'Save as Draft',
        'save_activate_label' => 'Save & Activate',
        'question_editor_label' => 'Question Editor',
        'question_type_label' => 'Question Type',
        'question_text_label' => 'Question Text',
        'enter_question_label' => 'Enter your question...',
        'low_label_suffix' => 'Low label (1)',
        'high_label_suffix' => 'High label (5)',
        'enter_option_label' => 'Enter option...',
        'used_times_label' => 'Used',
        'templates_label' => 'Survey Templates',
        'untitled_survey_label' => 'Untitled Survey',
        'your_answer_label' => 'Your answer...',
        'no_questions_preview_label' => 'No questions to preview',
        'hide_identity_label' => 'Hide respondent identity',
        'dynamic_questions_label' => 'Dynamic questions based on answers',
        'example_prompt_label' => 'For example: "How are you feeling today? How well did you sleep?"',
        'no_questions_bank_label' => 'No questions in the bank yet',
        'question_editor_title_label' => 'Question Editor',
        'add_question_title_label' => 'Add Question',
        'edit_question_title_label' => 'Edit Question',
        'update_action' => 'Update',
        'option_singular' => 'Option',
        'options_count_label' => 'options',
        'question_bank_modal_label' => 'Question Bank',
        'survey_templates_label' => 'Survey Templates',
        'used_times_suffix_label' => 'times',
        'start_speaking_label' => 'Click the button below and speak your survey questions clearly.',
        'recording_instruction_label' => 'Recording... Speak now',
        'processing_instruction_label' => 'Processing your audio with AI...',
        'answer_here_label' => 'Type your answer here...',
        'survey_title_example_label' => 'e.g., Weekly Wellness Check-In',
        'description_example_label' => 'Brief description of your survey...',
        'low_label_example' => 'e.g., Not at all',
        'high_label_example' => 'e.g., Very much',
        'start_survey_label' => 'Start Survey',
        'thank_you_label' => 'Thank You!',
        'responses_submitted_label' => 'Your responses have been submitted successfully.',
        'close_window_label' => 'You can close this window now.',
        'anonymous_responses_label' => 'Your responses are anonymous',
        'question_of_label' => 'of',
        'previous_label' => 'Previous',
        'skip_label' => 'Skip',
        'continue_label' => 'Continue',
        'submit_answer_label' => 'Submit Answer',
        'tap_to_record_label' => 'Tap to record your answer',
        'recording_tap_to_stop_label' => 'Recording... Tap to stop',
        'scale_low_label' => 'Not at all',
        'scale_high_label' => 'Very much',
        'delete_survey_confirm_label' => 'Are you sure? This will also delete all responses. This cannot be undone.',
        'delete_selected_surveys_confirm_label' => 'Are you sure you want to delete all selected surveys and their responses? This cannot be undone.',
        'last_label' => 'Last',
        'unknown_label' => 'Unknown',
        'abandoned_label' => 'Abandoned',
        'edit_scores_label' => 'Edit Scores',
        'save_changes_label' => 'Save Changes',
        'select_placeholder_label' => 'Select...',
        'no_response_label' => 'No response',
        'no_question_data_label' => 'No question data available',
        'ai_analysis_label' => 'AI Analysis',
        'recommendations_label' => 'Recommendations',
        'risk_level_label' => 'Risk Level',
        'no_surveys_completed_label' => 'No surveys completed yet.',
        'close_label' => 'Close',
        'no_surveys_available_label' => 'No surveys available.',
        'report_empty_title' => 'Create your first report',
        'report_empty_body' => 'Build beautiful, data-driven reports with our drag-and-drop editor.',
        'report_thumbnail_label' => 'Report thumbnail',
        'actions_label' => 'Actions',
        'untitled_report_label' => 'Untitled Report',
        'collection_label' => 'Collection',
        'collection_type_label' => 'Collection Type',
        'data_source_label' => 'Data Source',
        'data_source_body' => 'Choose where your questions come from.',
        'format_mode_label' => 'Format Mode',
        'schedule_configuration_label' => 'Schedule Configuration',
        'contact_scope_label' => 'Contact Scope',
        'reminder_settings_label' => 'Reminder Settings',
        'reminder_settings_body' => 'Configure how users will be reminded to complete collections.',
        'review_create_label' => 'Review & Create',
        'give_collection_name_label' => 'Give your collection a name and choose its type.',
        'description_optional_label' => 'Description (optional)',
        'what_collection_for_label' => 'What is this collection for?',
        'select_survey_label' => 'Select Survey',
        'no_active_surveys_label' => 'No active surveys available.',
        'create_survey_first_label' => 'Create a survey first',
        'additional_questions_label' => 'Additional Questions',
        'inline_questions_label' => 'Inline Questions',
        'add_question_prefix_label' => 'Add Question',
        'format_collect_body' => 'How should data be collected?',
        'schedule_one_time_label' => 'This is a one-time collection. Set when it should start.',
        'schedule_configure_label' => 'Configure when data collection should occur.',
        'schedule_type_label' => 'Schedule Type',
        'every_label' => 'Every',
        'period_label' => 'Period',
        'day_plural_label' => 'Day(s)',
        'week_plural_label' => 'Week(s)',
        'month_plural_label' => 'Month(s)',
        'select_days_label' => 'Select Days',
        'trigger_event_label' => 'Trigger Event',
        'select_event_label' => 'Select an event...',
        'survey_completed_label' => 'Survey Completed',
        'metric_threshold_label' => 'Metric Threshold Reached',
        'flag_raised_label' => 'Flag Raised',
        'collection_times_label' => 'Collection Times',
        'add_time_label' => 'Add Time',
        'start_date_label' => 'Start Date',
        'end_date_optional_label' => 'End Date (optional)',
        'contact_scope_body' => 'Who should be included in this collection?',
        'target_type_label' => 'Target Type',
        'staff_parents_label' => 'Staff/Parents',
        'filter_by_grade_label' => 'Filter by Grade (optional)',
        'filter_by_classroom_label' => 'Filter by Classroom (optional)',
        'filter_by_role_label' => 'Filter by Role (optional)',
        'estimated_count_label' => 'Estimated Count',
        'match_filters_label' => 'match your current filters.',
        'all_targets_label' => 'All',
        'enable_reminders_label' => 'Enable Reminders',
        'reminder_channels_label' => 'Reminder Channels',
        'send_reminder_before_label' => 'Send reminder before session',
        'follow_up_label' => 'Follow-up',
        'follow_up_after_label' => 'Follow-up after',
        'reminders_disabled_label' => 'Reminders are disabled for this collection.',
        'review_settings_label' => 'Review your collection settings before creating.',
        'basic_info_label' => 'Basic Info',
        'source_label' => 'Source',
        'format_label' => 'Format',
        'schedule_label' => 'Schedule',
        'contacts_label' => 'Contacts',
        'reminders_label' => 'Reminders',
        'enabled_via_label' => 'Enabled via',
        'create_activate_label' => 'Create & Activate',
        'save_draft_label' => 'Save as Draft',
        'at_label' => 'at',
        'data_collection_label' => 'Data Collection',
        'create_data_collection_label' => 'Create Data Collection',
        'collection_empty_title' => 'Create your first data collection',
        'collection_empty_body' => 'Set up recurring data collection to systematically gather progress monitoring data, check-ins, and insights from learners, staff, or parents.',
        'sessions_label' => 'sessions',
        'entries_label' => 'entries',
        'next_label' => 'Next',
        'linked_to_survey_label' => 'Linked to survey',
        'updated_ago_label' => 'Updated',
        'delete_collection_label' => 'Delete Collection',
        'delete_collection_confirm_label' => 'Are you sure? This will also delete all sessions and entries. This cannot be undone.',
        'distribution_empty_title' => 'Create your first distribution',
        'distribution_empty_body' => 'Send reports and messages to targeted groups via email or SMS. Set up one-time or recurring campaigns.',
        'create_distribution_label' => 'Create Distribution',
        'search_distributions_placeholder' => 'Search distributions...',
        'all_channels_label' => 'All Channels',
        'channel_label' => 'Channel',
        'basics_label' => 'Basics',
        'basics_summary_label' => 'Title, channel, and frequency',
        'distribution_title_placeholder' => 'e.g., Weekly Progress Report',
        'distribution_description_placeholder' => 'Brief description of this distribution...',
        'email_label' => 'Email',
        'frequency_label' => 'Frequency',
        'content_label' => 'Content',
        'report_link_label' => 'Report link',
        'custom_message_label' => 'Custom message',
        'report_link_or_message_label' => 'Report link or custom message',
        'content_type_label' => 'Content Type',
        'link_report_label' => 'Link Report',
        'attach_report_label' => 'Attach or link to an existing report',
        'compose_message_label' => 'Compose your own message',
        'select_report_label' => 'Select Report',
        'select_report_placeholder' => 'Select a report...',
        'report_mode_label' => 'Report Mode',
        'live_link_label' => 'Live Link',
        'realtime_data_label' => 'Real-time data',
        'pdf_snapshot_label' => 'PDF Snapshot',
        'static_attachment_label' => 'Static attachment',
        'subject_line_label' => 'Subject Line',
        'subject_line_placeholder' => 'e.g., Your Weekly Progress Report',
        'message_label' => 'Message',
        'message_placeholder' => 'Type your message here. Click merge fields below to insert them...',
        'merge_fields_help_label' => 'Click to insert merge fields:',
        'selected_list_label' => 'Selected list',
        'contacts_selected_label' => 'contacts selected',
        'recipients_description_label' => 'Who receives this distribution',
        'contact_list_label' => 'Contact List',
        'send_to_contact_list_label' => 'Send to an existing contact list',
        'individual_contacts_label' => 'Individual Contacts',
        'select_specific_contacts_label' => 'Select specific contacts',
        'select_contact_list_label' => 'Select Contact List',
        'select_list_placeholder' => 'Select a list...',
        'no_contact_lists_available_label' => 'No contact lists available.',
        'create_one_label' => 'Create one',
        'schedule_description_label' => 'When to send',
        'send_immediately_label' => 'Send immediately when activated',
        'scheduled_for_label' => 'Scheduled for',
        'configure_recurring_schedule_label' => 'Configure recurring schedule',
        'schedule_specific_datetime_label' => 'Schedule for a specific date/time',
        'date_time_label' => 'Date & Time',
        'timezone_label' => 'Timezone',
        'eastern_time_label' => 'Eastern Time',
        'central_time_label' => 'Central Time',
        'mountain_time_label' => 'Mountain Time',
        'pacific_time_label' => 'Pacific Time',
        'interval_label' => 'Interval (Daily/Weekly/Monthly)',
        'custom_days_label' => 'Custom Days',
        'days_of_week_label' => 'Days of Week',
        'send_time_label' => 'Send Time',
        'send_now_label' => 'Send Now',
        'schedule_action_label' => 'Schedule',
        'total_deliveries_label' => 'Total Deliveries',
        'messages_sent_label' => 'Messages Sent',
        'opens_label' => 'Opens',
        'avg_open_rate_label' => 'Avg. Open Rate',
        'distribution_details_label' => 'Distribution Details',
        'created_label' => 'Created',
        'by_label' => 'by',
        'message_preview_label' => 'Message Preview',
        'subject_label' => 'Subject',
        'body_label' => 'Body',
        'delivery_history_label' => 'Delivery History',
        'deliveries_will_appear_label' => 'Deliveries will appear here once the distribution is sent.',
        'send_distribution_label' => 'Send Distribution',
        'send_distribution_confirm_label' => 'Are you sure you want to send this distribution now? It will be sent to all recipients.',
        'sent_label' => 'sent',
        'opened_label' => 'opened',
        'clicked_label' => 'clicked',
        'recipients_label' => 'Recipients',
        'deliveries_label' => 'Deliveries',
        'next_send_label' => 'Next Send',
        'scheduled_label' => 'Scheduled',
        'recurring_label' => 'Recurring',
        'one_time_label' => 'One-time',
        'distribution_label' => 'Distribution',
        'delete_distribution_label' => 'Delete Distribution',
        'delete_distribution_confirm_label' => 'Are you sure? This will also delete all delivery history. This cannot be undone.',
        'individuals_label' => 'individuals',
        'to_label' => 'To',
        // Core app areas
        'dashboard_singular' => 'Dashboard',
        'dashboard_plural' => 'Dashboards',
        'report_singular' => 'Report',
        'report_plural' => 'Reports',
        'survey_singular' => 'Survey',
        'survey_plural' => 'Surveys',
        'contact_singular' => 'Contact',
        'contact_plural' => 'Contacts',
        'resource_singular' => 'Resource',
        'resource_plural' => 'Resources',
        'provider_singular' => 'Provider',
        'provider_plural' => 'Providers',
        'program_singular' => 'Program',
        'program_plural' => 'Programs',
        'content_singular' => 'Content',
        'content_plural' => 'Content',
        'plan_singular' => 'Plan',
        'plan_plural' => 'Plans',
        'collection_singular' => 'Collection',
        'collection_plural' => 'Collections',
        'distribution_singular' => 'Distribution',
        'distribution_plural' => 'Distributions',
        'alert_singular' => 'Alert',
        'alert_plural' => 'Alerts',
        'message_singular' => 'Message',
        'message_plural' => 'Messages',
        'notification_singular' => 'Notification',
        'notification_plural' => 'Notifications',
        'sub_organization_singular' => 'Sub-Organization',
        'sub_organization_plural' => 'Sub-Organizations',
        'seller_singular' => 'Seller',
        'seller_plural' => 'Sellers',
        'learner_singular' => 'Learner',
        'learner_plural' => 'Learners',
        'user_singular' => 'User',
        'user_plural' => 'Users',
        'organization_singular' => 'Organization',
        'organization_plural' => 'Organizations',
        'entry_singular' => 'Entry',
        'entry_plural' => 'Entries',
        // Time periods
        'period_singular' => 'Semester',
        'period_plural' => 'Semesters',
        // Learning units
        'course_singular' => 'Course',
        'course_plural' => 'Courses',
        'module_singular' => 'Module',
        'module_plural' => 'Modules',
        'step_singular' => 'Step',
        'step_plural' => 'Steps',
        'lesson_singular' => 'Lesson',
        'lesson_plural' => 'Lessons',
        // People
        'learner_singular' => 'Learner',
        'learner_plural' => 'Learners',
        'instructor_singular' => 'Instructor',
        'instructor_plural' => 'Instructors',
        'mentor_singular' => 'Mentor',
        'mentor_plural' => 'Mentors',
        'facilitator_singular' => 'Facilitator',
        'facilitator_plural' => 'Facilitators',
        // Groups
        'cohort_singular' => 'Cohort',
        'cohort_plural' => 'Cohorts',
        'organization_singular' => 'Organization',
        'organization_plural' => 'Organizations',
        // Credentials
        'certificate_singular' => 'Certificate',
        'certificate_plural' => 'Certificates',
        'badge_singular' => 'Badge',
        'badge_plural' => 'Badges',
        // Actions
        'enroll_action' => 'Enroll',
        'complete_action' => 'Complete',
        'progress_label' => 'Progress',
        'create_action' => 'Create',
        'new_action' => 'New',
        'add_action' => 'Add',
        'view_action' => 'View',
        'manage_action' => 'Manage',
        'search_action' => 'Search',
        'learn_more_action' => 'Learn More',
        'contact_us_action' => 'Contact Us',
        'become_action' => 'Become',
        'send_action' => 'Send',
        'assign_action' => 'Assign',
        'open_action' => 'Open',
        'edit_action' => 'Edit',
        'delete_action' => 'Delete',
        'duplicate_action' => 'Duplicate',
        'activate_action' => 'Activate',
        'pause_action' => 'Pause',
        'resume_action' => 'Resume',
        'cancel_action' => 'Cancel',
        'select_action' => 'Select',
        'continue_action' => 'Continue',
        'save_action' => 'Save',
    ];

    /**
     * Get the organization.
     */
    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class, 'org_id');
    }

    /**
     * Get a status label (custom or default).
     */
    public function getStatusLabel(string $key): string
    {
        $labels = $this->status_labels ?? [];

        return $labels[$key] ?? self::DEFAULT_STATUS_LABELS[$key] ?? ucfirst(str_replace('_', ' ', $key));
    }

    /**
     * Get a risk label (custom or default).
     */
    public function getRiskLabel(string $key): string
    {
        $labels = $this->risk_labels ?? [];

        return $labels[$key] ?? self::DEFAULT_RISK_LABELS[$key] ?? ucfirst($key);
    }

    /**
     * Get all status labels (merged with defaults).
     */
    public function getAllStatusLabels(): array
    {
        return array_merge(self::DEFAULT_STATUS_LABELS, $this->status_labels ?? []);
    }

    /**
     * Get all risk labels (merged with defaults).
     */
    public function getAllRiskLabels(): array
    {
        return array_merge(self::DEFAULT_RISK_LABELS, $this->risk_labels ?? []);
    }

    /**
     * Get a setting value.
     */
    public function getSetting(string $key, $default = null)
    {
        $settings = $this->settings ?? [];

        return $settings[$key] ?? $default;
    }

    /**
     * Set a setting value.
     */
    public function setSetting(string $key, $value): void
    {
        $settings = $this->settings ?? [];
        $settings[$key] = $value;
        $this->settings = $settings;
        $this->save();
    }

    /**
     * Get or create settings for an organization.
     */
    public static function forOrganization(int $orgId): self
    {
        return self::firstOrCreate(['org_id' => $orgId]);
    }

    /**
     * Get a terminology label (custom or default).
     */
    public function getTerm(string $key): string
    {
        $terminology = $this->terminology ?? [];

        return $terminology[$key] ?? self::DEFAULT_TERMINOLOGY[$key] ?? ucfirst(str_replace('_', ' ', $key));
    }

    /**
     * Get all terminology labels (merged with defaults).
     */
    public function getAllTerminology(): array
    {
        return array_merge(self::DEFAULT_TERMINOLOGY, $this->terminology ?? []);
    }

    /**
     * Set a terminology label.
     */
    public function setTerm(string $key, string $value): void
    {
        $terminology = $this->terminology ?? [];
        $terminology[$key] = $value;
        $this->terminology = $terminology;
        $this->save();
    }

    /**
     * Set multiple terminology labels at once.
     */
    public function setTerminology(array $labels): void
    {
        $terminology = $this->terminology ?? [];
        $this->terminology = array_merge($terminology, $labels);
        $this->save();
    }

    /**
     * Reset terminology to defaults.
     */
    public function resetTerminology(): void
    {
        $this->terminology = [];
        $this->save();
    }

    /**
     * Get terminology categories for admin UI.
     */
    public static function getTerminologyCategories(): array
    {
        return [
            'Navigation & UI' => [
                'home_label',
                'workspace_label',
                'settings_label',
                'help_center_label',
                'help_label',
                'help_options_label',
                'search_help_articles_placeholder',
                'search_articles_placeholder',
                'search_results_label',
                'view_all_results_label',
                'view_all_search_results_label',
                'no_articles_found_label',
                'try_advanced_search_label',
                'popular_articles_label',
                'featured_articles_label',
                'browse_by_topic_label',
                'browse_by_category_label',
                'quick_links_label',
                'browse_all_articles_label',
                'browse_help_center_label',
                'page_tour_label',
                'guided_walkthrough_label',
                'contact_support_label',
                'send_us_message_label',
                'help_admin_label',
                'manage_articles_hints_label',
                'close_help_label',
                'need_help_label',
                'show_tooltips_label',
                'hide_tooltips_label',
                'help_hints_description_label',
                'start_page_tour_label',
                'tooltips_step_through_label',
                'browse_articles_guides_label',
                'create_tooltips_label',
                'exit_creator_mode_label',
                'help_tips_description_label',
                'manage_tooltips_label',
                'view_edit_tooltips_label',
                'find_answers_label',
                'showing_results_for_label',
                'all_categories_label',
                'all_status_label',
                'all_statuses_label',
                'drafts_label',
                'no_results_found_label',
                'adjust_search_label',
                'adjust_filters_label',
                'min_read_label',
                'views_label',
                'articles_label',
                'article_singular',
                'categories_label',
                'category_singular',
                'tooltips_label',
                'tooltip_singular',
                'help_documentation_label',
                'organize_articles_label',
                'contextual_tips_label',
                'new_article_label',
                'no_categories_yet_label',
                'create_categories_help_label',
                'create_first_category_label',
                'parent_label',
                'inactive_label',
                'confirm_delete_category_label',
                'name_label',
                'category_name_placeholder',
                'category_slug_placeholder',
                'category_description_placeholder',
                'icon_label',
                'parent_category_label',
                'none_top_level_label',
                'sort_order_label',
                'manage_tooltips_page_label',
                'visual_editor_label',
                'open_visual_editor_label',
                'this_page_label',
                'no_tooltips_yet_label',
                'add_tooltips_help_label',
                'add_first_tooltip_label',
                'section_label',
                'selector_label',
                'position_label',
                'has_video_label',
                'tooltip_position_label',
                'pick_label',
                'pick_element_label',
                'pick_element_help_label',
                'section_id_label',
                'section_id_placeholder',
                'css_selector_label',
                'selector_placeholder',
                'tooltip_title_placeholder',
                'tooltip_description_placeholder',
                'video_url_hint_placeholder',
                'confirm_delete_tooltip_label',
                'how_tooltips_work_label',
                'section_help_label',
                'selector_help_label',
                'position_help_label',
                'enable_tooltips_help_label',
                'tooltip_creator_mode_label',
                'click_add_tooltip_label',
                'page_label',
                'exit_creator_label',
                'add_new_tooltip_label',
                'for_label',
                'tooltip_position_above_label',
                'tooltip_position_below_label',
                'tooltip_position_left_label',
                'tooltip_position_right_label',
                'video_url_supports_label',
                'saving_label',
                'slug_label',
                'select_category_placeholder',
                'content_markdown_label',
                'content_markdown_placeholder',
                'supports_markdown_label',
                'article_title_placeholder',
                'slug_placeholder',
                'excerpt_optional_label',
                'excerpt_placeholder',
                'auto_generated_excerpt_label',
                'video_url_optional_label',
                'video_url_placeholder',
                'search_keywords_label',
                'search_keywords_placeholder',
                'search_keywords_help_label',
                'target_roles_optional_label',
                'target_roles_help_label',
                'create_article_label',
                'edit_article_label',
                'confirm_delete_article_label',
                'pages_label',
                'all_articles_label',
                'title_label',
                'category_label',
                'feedback_label',
                'updated_label',
                'no_articles_yet_label',
                'create_first_article_label',
                'uncategorized_label',
                'manage_label',
                'manage_kb_articles_label',
                'subcategories_label',
                'articles_in_category_label',
                'check_back_soon_label',
                'create_first_help_article_label',
                'ago_label',
                'related_articles_label',
                'was_this_helpful_label',
                'copied_label',
                'copy_link_label',
                'share_label',
                'share_article_label',
                'email_link_label',
                'admin_view_label',
                'article_id_label',
                'still_need_help_label',
                'cant_find_label',
                'support_team_help_label',
                'most_popular_label',
                'preview_label',
                'remove_featured_label',
                'mark_featured_label',
                'published_label',
                'draft_label',
                'back_label',
                'general_label',
                'marketplace_label',
                'moderation_label',
                'collect_label',
                'distribute_label',
                'terminology_label',
                'notifications_label',
                'profile_label',
                'security_label',
                'yes_label',
                'no_label',
                'status_label',
                'score_label',
                'history_label',
                'assigned_label',
                'suggested_label',
                'available_label',
                'tag_singular',
                'tag_plural',
                'risk_label',
                'iep_status_label',
                'ell_status_label',
                'details_label',
                'date_of_birth_label',
                'gender_label',
                'enrolled_label',
                'strategic_label',
                'tab_label',
                'view_in_label',
                'notes_label',
                'activity_label',
                'timeline_label',
                'overview_label',
                'total_label',
                'metrics_label',
                'good_standing_label',
                'low_risk_label',
                'high_risk_label',
                'active_label',
                'currently_running_label',
                'completed_this_week_label',
                'responses_received_label',
                'assignment_singular',
                'assignment_plural',
                'week_label',
                'back_to_label',
                'questions_label',
                'question_singular',
                'required_label',
                'recent_label',
                'responses_label',
                'in_progress_label',
                'completion_rate_label',
                'statistics_label',
                'delivery_label',
                'channel_singular',
                'channel_plural',
                'phone_number_label',
                'recipient_singular',
                'recipient_plural',
                'anonymous_label',
                'enabled_label',
                'disabled_label',
                'allowed_label',
                'ai_follow_up_label',
                'voice_responses_label',
                'push_label',
                'confirm_label',
                'confirm_delete_survey_label',
                'web_link_label',
                'sms_label',
                'voice_call_label',
                'whatsapp_label',
                'all_label',
                'type_label',
                'organization_label',
                'selected_label',
                'clear_label',
                'grid_view_label',
                'list_view_label',
                'table_view_label',
                'survey_empty_title',
                'survey_empty_body',
                'ai_created_label',
                'total_sent_label',
                'pending_label',
                'delivered_label',
                'completed_label',
                'failed_label',
                'select_recipients_label',
                'staff_label',
                'search_by_label',
                'add_phone_manually_label',
                'no_recipients_found_label',
                'recipient_selected_label',
                'clear_all_label',
                'schedule_delivery_label',
                'send_at_label',
                'sending_label',
                'recent_deliveries_label',
                'no_deliveries_label',
                'tips_for_demo_label',
                'delivery_successful_label',
                'delivery_complete_label',
                'successful_label',
                'done_label',
                'manual_phone_help_label',
                'choose_how_label',
                'ai_chat_builder_label',
                'ai_chat_builder_body',
                'natural_conversation_label',
                'ai_suggestions_label',
                'quick_refinement_label',
                'ai_powered_label',
                'not_configured_label',
                'voice_builder_label',
                'voice_builder_body',
                'hands_free_label',
                'audio_transcription_label',
                'easy_editing_label',
                'form_builder_label',
                'form_builder_body',
                'full_control_label',
                'question_bank_label',
                'advanced_options_label',
                'classic_label',
                'start_from_template_label',
                'view_all_templates_label',
                'featured_label',
                'uses_label',
                'ai_assistant_label',
                'describe_needs_label',
                'finish_edit_label',
                'survey_preview_label',
                'no_questions_yet_label',
                'start_chatting_label',
                'back_to_mode_selection_label',
                'voice_survey_builder_label',
                'voice_survey_builder_body',
                'start_recording_label',
                'stop_recording_label',
                'transcribing_label',
                'recording_label',
                'processing_audio_label',
                'transcription_label',
                'extracted_questions_label',
                'no_questions_detected_label',
                'record_again_label',
                'continue_to_editor_label',
                'basic_information_label',
                'survey_title_label',
                'description_label',
                'survey_type_label',
                'question_bank_button_label',
                'add_question_label',
                'no_questions_added_label',
                'add_first_question_label',
                'options_label',
                'low_label',
                'high_label',
                'remove_option_label',
                'add_option_label',
                'required_question_label',
                'estimated_duration_label',
                'minutes_label',
                'delivery_channels_label',
                'preview_survey_label',
                'save_as_draft_label',
                'save_activate_label',
                'question_editor_label',
                'question_type_label',
                'question_text_label',
                'enter_question_label',
                'low_label_suffix',
                'high_label_suffix',
                'enter_option_label',
                'used_times_label',
                'templates_label',
                'untitled_survey_label',
                'your_answer_label',
                'no_questions_preview_label',
                'hide_identity_label',
                'dynamic_questions_label',
                'example_prompt_label',
                'no_questions_bank_label',
                'question_editor_title_label',
                'add_question_title_label',
                'edit_question_title_label',
                'update_action',
                'option_singular',
                'options_count_label',
                'question_bank_modal_label',
                'survey_templates_label',
                'used_times_suffix_label',
                'start_speaking_label',
                'recording_instruction_label',
                'processing_instruction_label',
                'answer_here_label',
                'survey_title_example_label',
                'description_example_label',
                'low_label_example',
                'high_label_example',
                'start_survey_label',
                'thank_you_label',
                'responses_submitted_label',
                'close_window_label',
                'anonymous_responses_label',
                'question_of_label',
                'previous_label',
                'skip_label',
                'continue_label',
                'submit_answer_label',
                'tap_to_record_label',
                'recording_tap_to_stop_label',
                'scale_low_label',
                'scale_high_label',
                'delete_survey_confirm_label',
                'delete_selected_surveys_confirm_label',
                'last_label',
                'unknown_label',
                'abandoned_label',
                'edit_scores_label',
                'save_changes_label',
                'select_placeholder_label',
                'no_response_label',
                'no_question_data_label',
                'ai_analysis_label',
                'recommendations_label',
                'risk_level_label',
                'no_surveys_completed_label',
                'close_label',
                'no_surveys_available_label',
                'report_empty_title',
                'report_empty_body',
                'draft_label',
                'published_label',
                'updated_label',
                'report_thumbnail_label',
                'actions_label',
                'untitled_report_label',
                'basic_information_label',
                'collection_label',
                'collection_type_label',
                'data_source_label',
                'data_source_body',
                'format_mode_label',
                'schedule_configuration_label',
                'contact_scope_label',
                'reminder_settings_label',
                'reminder_settings_body',
                'review_create_label',
                'give_collection_name_label',
                'title_label',
                'description_optional_label',
                'what_collection_for_label',
                'select_survey_label',
                'no_active_surveys_label',
                'create_survey_first_label',
                'additional_questions_label',
                'inline_questions_label',
                'add_question_prefix_label',
                'format_collect_body',
                'schedule_one_time_label',
                'schedule_configure_label',
                'schedule_type_label',
                'every_label',
                'at_label',
                'period_label',
                'day_plural_label',
                'week_plural_label',
                'month_plural_label',
                'select_days_label',
                'trigger_event_label',
                'select_event_label',
                'survey_completed_label',
                'metric_threshold_label',
                'flag_raised_label',
                'collection_times_label',
                'add_time_label',
                'start_date_label',
                'end_date_optional_label',
                'contact_scope_body',
                'target_type_label',
                'staff_parents_label',
                'filter_by_grade_label',
                'filter_by_classroom_label',
                'filter_by_role_label',
                'estimated_count_label',
                'match_filters_label',
                'all_targets_label',
                'enable_reminders_label',
                'reminder_channels_label',
                'send_reminder_before_label',
                'follow_up_label',
                'follow_up_after_label',
                'reminders_disabled_label',
                'review_settings_label',
                'basic_info_label',
                'source_label',
                'format_label',
                'schedule_label',
                'contacts_label',
                'reminders_label',
                'enabled_via_label',
                'create_activate_label',
                'save_draft_label',
                'back_label',
                'data_collection_label',
                'create_data_collection_label',
                'collection_empty_title',
                'collection_empty_body',
                'sessions_label',
                'entries_label',
                'next_label',
                'linked_to_survey_label',
                'updated_ago_label',
                'delete_collection_label',
                'delete_collection_confirm_label',
                'distribution_empty_title',
                'distribution_empty_body',
                'create_distribution_label',
                'search_distributions_placeholder',
                'all_channels_label',
                'channel_label',
                'basics_label',
                'basics_summary_label',
                'distribution_title_placeholder',
                'distribution_description_placeholder',
                'email_label',
                'frequency_label',
                'content_label',
                'report_link_label',
                'custom_message_label',
                'report_link_or_message_label',
                'content_type_label',
                'link_report_label',
                'attach_report_label',
                'compose_message_label',
                'select_report_label',
                'select_report_placeholder',
                'report_mode_label',
                'live_link_label',
                'realtime_data_label',
                'pdf_snapshot_label',
                'static_attachment_label',
                'subject_line_label',
                'subject_line_placeholder',
                'message_label',
                'message_placeholder',
                'merge_fields_help_label',
                'selected_list_label',
                'contacts_selected_label',
                'recipients_description_label',
                'contact_list_label',
                'send_to_contact_list_label',
                'individual_contacts_label',
                'select_specific_contacts_label',
                'select_contact_list_label',
                'select_list_placeholder',
                'no_contact_lists_available_label',
                'create_one_label',
                'schedule_description_label',
                'send_immediately_label',
                'scheduled_for_label',
                'configure_recurring_schedule_label',
                'schedule_specific_datetime_label',
                'date_time_label',
                'timezone_label',
                'eastern_time_label',
                'central_time_label',
                'mountain_time_label',
                'pacific_time_label',
                'interval_label',
                'custom_days_label',
                'days_of_week_label',
                'send_time_label',
                'send_now_label',
                'schedule_action_label',
                'total_deliveries_label',
                'messages_sent_label',
                'opens_label',
                'avg_open_rate_label',
                'distribution_details_label',
                'created_label',
                'by_label',
                'message_preview_label',
                'subject_label',
                'body_label',
                'delivery_history_label',
                'deliveries_will_appear_label',
                'send_distribution_label',
                'send_distribution_confirm_label',
                'sent_label',
                'opened_label',
                'clicked_label',
                'recipients_label',
                'deliveries_label',
                'next_send_label',
                'scheduled_label',
                'recurring_label',
                'one_time_label',
                'distribution_label',
                'delete_distribution_label',
                'delete_distribution_confirm_label',
                'individuals_label',
                'to_label',
            ],
            'Core App Areas' => [
                'dashboard_singular', 'dashboard_plural',
                'report_singular', 'report_plural',
                'survey_singular', 'survey_plural',
                'contact_singular', 'contact_plural',
                'resource_singular', 'resource_plural',
                'provider_singular', 'provider_plural',
                'program_singular', 'program_plural',
                'content_singular', 'content_plural',
                'plan_singular', 'plan_plural',
                'collection_singular', 'collection_plural',
                'distribution_singular', 'distribution_plural',
                'alert_singular', 'alert_plural',
                'message_singular', 'message_plural',
                'notification_singular', 'notification_plural',
                'sub_organization_singular', 'sub_organization_plural',
                'seller_singular', 'seller_plural',
                'learner_singular', 'learner_plural',
                'user_singular', 'user_plural',
                'organization_singular', 'organization_plural',
                'entry_singular', 'entry_plural',
            ],
            'Time Periods' => ['period_singular', 'period_plural'],
            'Learning Units' => ['course_singular', 'course_plural', 'module_singular', 'module_plural', 'step_singular', 'step_plural', 'lesson_singular', 'lesson_plural'],
            'People' => ['learner_singular', 'learner_plural', 'instructor_singular', 'instructor_plural', 'mentor_singular', 'mentor_plural', 'facilitator_singular', 'facilitator_plural'],
            'Groups' => ['cohort_singular', 'cohort_plural', 'organization_singular', 'organization_plural'],
            'Credentials' => ['certificate_singular', 'certificate_plural', 'badge_singular', 'badge_plural'],
            'Actions & Labels' => ['enroll_action', 'complete_action', 'progress_label', 'create_action', 'new_action', 'add_action', 'view_action', 'manage_action', 'search_action', 'learn_more_action', 'contact_us_action', 'become_action', 'send_action', 'assign_action', 'open_action', 'edit_action', 'delete_action', 'duplicate_action', 'activate_action', 'pause_action', 'resume_action', 'cancel_action', 'select_action', 'continue_action', 'save_action'],
        ];
    }
}
